capture output

diff --git a/.github/workflows/build-test-push.yml b/.github/workflows/build-test-push.yml
--- a/.github/workflows/build-test-push.yml
+++ b/.github/workflows/build-test-push.yml
@@ -54,13 +54,23 @@ jobs:
       - name: SAM Local Invoke
         run: |
           aws sts assume-role --role-arn $LAMBDA_ROLE_ARN --role-session-name githubactionsgotestrolesession > creds
-          $(echo "export AWS_ACCESS_KEY_ID=$(echo $(cat creds) | sed -n 's/.*"AccessKeyId": "\([^"]*\)".*/\1/p')")
-          $(echo "export AWS_SECRET_ACCESS_KEY=$(echo $(cat creds) | sed -n 's/.*"SecretAccessKey": "\([^"]*\)".*/\1/p')")
-          $(echo "export AWS_SESSION_TOKEN=$(echo $(cat creds) | sed -n 's/.*"SessionToken": "\([^"]*\)".*/\1/p')")
+          export AWS_ACCESS_KEY_ID=$(cat creds | jq -r '.Credentials.AccessKeyId')
+          export AWS_SECRET_ACCESS_KEY=$(cat creds | jq -r '.Credentials.SecretAccessKey')
+          export AWS_SESSION_TOKEN=$(cat creds | jq -r '.Credentials.SessionToken')
           aws sts get-caller-identity
-          # Invoke the SAM function and check for error
-          ! sam local invoke InstanceSchedulerFunction --event event.json 2>&1 |grep -i error
+      
+          # Capture SAM output in a variable
+          SAM_OUTPUT=$(sam local invoke InstanceSchedulerFunction --event event.json 2>&1)
+          echo "$SAM_OUTPUT"
+      
+          # Check for errors in the output
+          if echo "$SAM_OUTPUT" | grep -i "error"; then
+            echo "Error detected in SAM invoke output."
+            exit 1
+          fi
+      
           unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
+      
       - name: Download Go Modules
         working-directory: instance-scheduler
         run: go mod download
